#ifndef _ALL_INCLUDE_H_
#define _ALL_INCLUDE_H_

#include <vtkVersion.h>
#include <vtkSmartPointer.h>
#include <vtkSTLReader.h>
#include <vtkRenderWindowInteractor.h>
#include <vtkRenderWindow.h>
#include <vtkRenderer.h>
#include <vtkActor.h>
#include <vtkCamera.h>
#include <vtkDataSetMapper.h>
#include <vtkPolyDataMapper.h>
#include <vtkPolyData.h>
#include <vtkActor.h>
#include <vtkProperty.h>
#include <vtkClipClosedSurface.h>
#include <vtkClipPolyData.h>
#include <vtkPlane.h>
#include <vtkPlaneCollection.h>
#include <vtkXMLPolyDataReader.h>
#include <vtkBooleanOperationPolyDataFilter.h>
#include <vtkTransform.h>
#include <vtkTransformPolyDataFilter.h>
#include <vtkInteractorStyleTrackballActor.h>
#include <vtkNamedColors.h>
#include <vtkSphereSource.h>
#include <vtkOrientedGlyphContourRepresentation.h>
#include <vtkContourWidget.h>
#include <vtkPolygonalSurfacePointPlacer.h>
#include <vtkLinearContourLineInterpolator.h>
#include <vtkCellPicker.h>
#include <vtkCallbackCommand.h>
#include <vtkAreaPicker.h>
#include <vtkCommand.h>
#include <vtkCoordinate.h>
#include <vtkUnstructuredGrid.h>
#include <vtkPentagonalPrism.h>
#include <vtkPlaneSource.h>
#include <vtkImplicitPolyDataDistance.h>
#include <vtkFloatArray.h>
#include <vtkTableBasedClipDataSet.h>
#include <vtkRectilinearGridGeometryFilter.h>
#include <vtkPointData.h>
#include <vtkConeSource.h>
#include <vtkPolygon.h>
#include <vtkDelaunay2D.h>
#include <opencv2/opencv.hpp>
#include <vtkBox.h>
#include <vtkElevationFilter.h>
#include <vtkImplicitBoolean.h>
#include <vtkElevationFilter.h>
#include <vtkDelaunay3D.h>
#include <vtkImplicitDataSet.h>
#include <vtkTriangleFilter.h>
#include <vtkLinearExtrusionFilter.h>
#include <vtkMath.h>


#endif